# Generated by Django 6.0.5 on 2026-06-02 09:20

import django.core.validators
import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('legal_address', models.CharField(max_length=100, verbose_name='юр Адрес')),
                ('unp', models.CharField(max_length=9, unique=True, verbose_name='УНП')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('dad_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('mechanic', 'Автомеханик'), ('admin', 'Админ')], max_length=8, verbose_name='Должность')),
                ('hourly_rate', models.FloatField(blank=True, null=True, verbose_name='часовая ставка')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.CharField(choices=[('wheels', 'колёса'), ('paintwork', 'покраска'), ('engine', 'двигатель'), ('electrical_system', 'электросистема'), ('suspension', 'подвеска'), ('other', 'прочее')], max_length=18, verbose_name='Тип работы')),
                ('arrival_time', models.DateTimeField(verbose_name='Время поступления авто')),
                ('work_start_time', models.DateTimeField(default=None, null=True, verbose_name='Время начала работы')),
                ('work_end_time', models.DateTimeField(default=None, null=True, verbose_name='Время окончания работ')),
                ('delivery_acceptance_time', models.DateTimeField(default=None, null=True, verbose_name='Время принятия работ')),
                ('price', models.FloatField(verbose_name='Цена работ')),
                ('car_number', models.CharField(max_length=8, verbose_name='Номер авто')),
                ('car_name', models.CharField(max_length=50, verbose_name=' Марка и модель авто')),
                ('comments', models.CharField(blank=True, max_length=200, verbose_name='Коментарии')),
                ('finding', models.CharField(choices=[('parking', 'стоянка'), ('box', 'рабочее пространство'), ('owner', 'уехала к владельцу')], default='parking', max_length=20, verbose_name='Местонахождение')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_as_admin', to='car_service.worker', verbose_name='Админ')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_as_worker', to='car_service.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес мастерской')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Вмещаемость мастерской')),
                ('parking_space', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Количество места на стоянке')),
                ('occupied_workshop_spaces', models.PositiveSmallIntegerField(verbose_name='занятые места в мастерской')),
                ('occupied_parking_spaces', models.PositiveSmallIntegerField(verbose_name='занятые места на парковке')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='car_service.company', verbose_name='Компания')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='car_service.workshop', verbose_name='Мастерская'),
        ),
    ]
