# Generated by Django 6.0.5 on 2026-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_acceptance_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Время принятия работ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_end_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Время окончания работ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_start_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='occupied_workshop_spaces',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='занятые места в мастерской'),
        ),
    ]
