# Generated by Django 6.0.5 on 2026-05-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('legal_address', models.CharField(max_length=100, verbose_name='юр Адрес')),
                ('UNP', models.CharField(max_length=9, verbose_name='УНП')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('mechanic', 'Автомеханик'), ('admin', 'Админ')], max_length=20, verbose_name='Должность')),
                ('hourly_rate', models.FloatField(blank=True, null=True, verbose_name='часовая ставка')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.CharField(max_length=200, verbose_name='Тип работы')),
                ('receipt_time', models.DateTimeField(verbose_name='Время поступления авто')),
                ('start_time', models.DateTimeField(verbose_name='Время начала работы')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания работ')),
                ('time_of_delivery', models.DateTimeField(verbose_name='Время принятия работ')),
                ('price', models.FloatField(verbose_name='Цена работ')),
                ('car_number', models.CharField(max_length=8, verbose_name='Номер авто')),
                ('name_car', models.CharField(max_length=50, verbose_name=' Марка и модель авто')),
                ('comments', models.CharField(blank=True, max_length=200, verbose_name='Коментарии')),
                ('admin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_as_admin', to='myapp.worker', verbose_name='Админ')),
                ('worker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_as_worker', to='myapp.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс мастерской')),
                ('capacity', models.IntegerField(verbose_name='Вмещаемость мастерской')),
                ('parking_space', models.IntegerField(verbose_name='Количество места на стоянке')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='myapp.company', verbose_name='Компания')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='myapp.workshop', verbose_name='Мастерская'),
        ),
    ]
